##### Makefile.in for Scidc for Unix operating systems.

# Scidc version:
#-----------------------------------------------------------------------
SCIDB_VERSION	= -DSCIDB_VERSION="\"26.06.15 b1 Beta\""
SCIDB_REVISION	= -DSCIDB_REVISION="\"1493\""

# End of Makefile
