##### Makefile.in for Scidc for Unix operating systems.

# Scidc version:
#-----------------------------------------------------------------------
SCIDB_VERSION	= -DSCIDB_VERSION="\"1.1.126 BETA\""
SCIDB_REVISION	= -DSCIDB_REVISION="\"1493\""

# End of Makefile
