##### Makefile.in for Scidc for Unix operating systems.

# Scidc version:
#-----------------------------------------------------------------------
SCIDB_VERSION	= -DSCIDB_VERSION="26.07.12 b11 Beta"
SCIDB_REVISION	= -DSCIDB_REVISION="1497"

# End of Makefile
